export enum TestID {
  CURRENCY_BUTTON = 'CURRENCY_BUTTON',
  CURRENCY_OPTION = 'CURRENCY_OPTION',
  DROPDOWN_MENU_LABEL = 'DROPDOWN_MENU_LABEL',

  TOOLTIP_BUTTON = 'TOOLTIP_BUTTON',
  TOOLTIP_CONTENT = 'TOOLTIP_CONTENT',
  TOOLTIP_DEFAULT_ICON = 'TOOLTIP_DEFAULT_ICON',

  RATES_UNAVAILABLE = 'RATES_UNAVAILABLE',
  ACTUAL_PRICE = 'ACTUAL_PRICE',
}

